### ISSUE TITLE
php 7.4.2 does not support each

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#12]
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\htdocs\sed178\system\install\install.setup.php on line 56
**all system files need to be changed**

all files give error like this.

while(list($i,$x) = each($langlist))

**change**

foreach($langlist as $i => $x)

yes.

**Comment by SeditioCMS** [comment]
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\htdocs\sed178\system\functions.admin.php on line 559

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\sed178\system\functions.php on line 4842

**Comment by SeditioCMS** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\xampp\htdocs\sed178\plugins\slider\slider.php on line 86

**Comment by SeditioCMS** [comment]
<html>
<body>


<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\sed178\system\functions.php</b> on line <b>4293</b><br />
--
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\sed178\system\functions.php</b> on line <b>4293</b><br />
  | <br />
  | <b>Deprecated</b>:  The each() function is deprecated. This message will be suppressed on further calls in <b>C:\xampp\htdocs\sed178\system\core\admin\admin.home.inc.php</b> on line <b>93</b><br />


</body>
</html>

**Comment by SeditioCMS** [comment]
ated: Array and string offset access syntax with curly braces is deprecated in C:\xampp\htdocs\sed178\plugins\similarpages\similarpages.page.tags.php on line 106

Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\xampp\htdocs\sed178\plugins\slider\slider.php on line 86

**Comment by amrosio** [comment]
Hi, Kaan. Thank you! I have fixed many bugs for PHP 7.4 
After the new year there will be release 178 and seditio.org update :)
I myself am still on PHP 7.1, so errors are possible on versions newer.

**Comment by SeditioCMS** [comment]
> Hi, Kaan. Thank you! I have fixed many bugs for PHP 7.4 After the new year there will be release 178 and seditio.org update :) I myself am still on PHP 7.1, so errors are possible on versions newer.

I'm looking forward to it.
good to see you.
I love Seditio :)
Thanks.

**Comment by avego** [comment]
Kaan I love Seditio too. And probably there are only 3-4 of us left)))
First of all, I develop sites for my clients in Russia on Seditio, so I try to support him at least a little.
