### ISSUE TITLE
expects parameter 1 to be array

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#13]
Warning: reset() expects parameter 1 to be array, null given in C:\xampp\htdocs\sed178\system\core\pfs\pfs.inc.php on line 72

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\sed178\system\core\pfs\pfs.inc.php on line 73

Warning: reset() expects parameter 1 to be array, null given in C:\xampp\htdocs\sed178\system\core\pfs\pfs.inc.php on line 621

Warning: sort() expects parameter 1 to be array, null given in C:\xampp\htdocs\sed178\system\core\pfs\pfs.inc.php on line 622

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\sed178\system\core\pfs\pfs.inc.php on line 624

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\sed178\system\functions.php on line 4293

**Comment by avego** [comment]
Thank you!
This is also fixed.

**Comment by SeditioCMS** [comment]
> Thank you! This is also fixed.

Hi avego nice to see you.
Good to see old seditio users.

Php 7.4.xx
I'm testing a lot of bugs.
ckeditor is not working.

so you can test it on xamp server.
Thanks

**Comment by avego** [comment]
I will correct mistakes. I installed php version 7.4. and there are really a lot of them, mostly deprecated.

**Comment by avego** [comment]
Thank you friend Kaan, for not forgetting about Seditio. Perhaps Olivier will also return to Sedetio in his old age :)) I haven't communicated with him for 10 years. It is a pity that he abandoned his project.
