### ISSUE TITLE
forums.posts.inc bugs

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#14]
**u.user_extra1, u.user_extra2, u.user_extra3, u.user_extra4, u.user_extra5, u.user_extra6, u.user_extra7, u.user_extra8, u.user_extra9,**

they are not in the members table

https://github.com/sedteam/Seditio/blob/83cca98502af3b28b234edfb8be33d4fdc3562c2/system/core/forums/forums.posts.inc.php#L339

**install.database**
https://github.com/sedteam/Seditio/blob/83cca98502af3b28b234edfb8be33d4fdc3562c2/system/install/install.database.php#L445

**Comment by avego** [comment]
I' fix this error https://github.com/sedteam/Seditio/commit/41ad354bb447bbaf8466df66227a53279a18ff5f 

I removed them from pages and users. Extra fields are now created through the **Directories & Extra fields tool**
/admin/tools
