### ISSUE TITLE
new bugs PHP Notice:  Undefined index: qcount

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#16]
what was the reason

[Thu Dec 09 10:04:15.878499 2021] [php7:notice] [pid 5164:tid 1872] [client ::1:61369] PHP Notice:  Undefined index: qcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 221,
[Thu Dec 09 10:04:15.879497 2021] [php7:notice] [pid 5164:tid 1872] [client ::1:61369] PHP Notice:  Undefined index: tcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 231
[Thu Dec 09 10:04:15.879497 2021] [php7:notice] [pid 5164:tid 1872] [client ::1:61369] PHP Notice:  Undefined index: devmode in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 232, 
[Thu Dec 09 10:04:18.397347 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: qcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 221,
[Thu Dec 09 10:04:18.397347 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: tcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 231,
[Thu Dec 09 10:04:18.397347 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: devmode in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 232,
[Thu Dec 09 10:04:19.844146 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: qcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 221,
[Thu Dec 09 10:04:19.844146 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: tcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 231,
[Thu Dec 09 10:04:19.844146 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: devmode in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 232,
[Thu Dec 09 10:04:21.124994 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: qcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 221, 
[Thu Dec 09 10:04:21.125993 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: tcount in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 231,
[Thu Dec 09 10:04:21.125993 2021] [php7:notice] [pid 5164:tid 1836] [client ::1:61374] PHP Notice:  Undefined index: devmode in C:\\xampp\\htdocs\\satilan1\\system\\database.mysqli.php on line 232,

**Comment by avego** [comment]
These are not errors, but notifications about uninitialized variables. Configure your normal php and set in php.ini:
error_reporting = E_ALL & ~ E_NOTICE
Those. show all errors except notifications !!!
