### ISSUE TITLE
image upload pfs sed 178 php 7.4.2 Warning: imagecreatefromjpeg()

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#17]
Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x47 0x49 in C:\xampp\htdocs\sed178\system\functions.php on line 1837

Warning: imagecreatefromjpeg(): 'datas/users/1-1639485450-e7b.jpg' is not a valid JPEG file in C:\xampp\htdocs\sed178\system\functions.php on line 1837

Warning: imagesx() expects parameter 1 to be resource, bool given in C:\xampp\htdocs\sed178\system\functions.php on line 1841

Warning: imagesy() expects parameter 1 to be resource, bool given in C:\xampp\htdocs\sed178\system\functions.php on line 1842

Warning: Division by zero in C:\xampp\htdocs\sed178\system\functions.php on line 1852

Warning: imagecreatetruecolor() expects parameter 2 to be int, float given in C:\xampp\htdocs\sed178\system\functions.php on line 1865

Warning: imagealphablending() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1867

Warning: imagesavealpha() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1868

Warning: imagecolorallocate() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1870

Warning: imagefilledrectangle() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1871

Warning: imagecopyresampled() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1876

Warning: imagejpeg() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1912

Warning: imagedestroy() expects parameter 1 to be resource, null given in C:\xampp\htdocs\sed178\system\functions.php on line 1916

Warning: imagedestroy() expects parameter 1 to be resource, bool given in C:\xampp\htdocs\sed178\system\functions.php on line 1917

**Comment by avego** [comment]
Hi Kaan. I could not verify it, I have no such errors on PHP 7.4 How can I simulate this?

May be the problem is in the jpg file **1639485450-e7b.jpg** itself and is it broken? (is not a valid JPEG file in)
