### ISSUE TITLE
The problem with editing the menu through the admin panel 

### ISSUE THREAD

**Issue by motor2hg** [sedteam/Seditio#20]
In header.tpl we have {PHP.sed_menu.1.childrens} and in the admin panel we pass menu parameters to {PHP.cfg.menu1} but there is no such parameter in the skin. Maybe I'm wrong, but using the admin panel we cannot set menu items. 
Obviously, this release added a new menu editor, the old one is still a bit confusing.

**Comment by avego** [comment]
The menu in the skin is displayed using a new tool. Look in the admin panel **Menu manager**
