### ISSUE TITLE
It is not possible to write a comment 

### ISSUE THREAD

**Issue by motor2hg** [sedteam/Seditio#21]
No comment window.

**Comment by avego** [comment]
The skin is still being finalized. I have inserted tags for displaying comments and rating. It remains to arrange the visual part. https://github.com/sedteam/Seditio/commit/0e439f93331535e01bf216c5315f560fc56753bd#diff-dbf1a5625153c98e83b7f21624bc4b32bad8fbbc6b625043ea342ccdf75f4c9b
