### ISSUE TITLE
The block of social networks 

### ISSUE THREAD

**Issue by motor2hg** [sedteam/Seditio#25]
The block of social networks does not work correctly, or I cannot figure out how to write values there so that this block starts to be displayed?

**Comment by avego** [comment]
links to soc. networks are written when editing header.tpl and footer.tpl

**Comment by motor2hg** [comment]
It's strange, I tested the site on Mac OS and there are icons of social networks in all browsers, UNDERSTANDING in Windows they were devoured by AdGuard !!! I am sorry.
