### ISSUE TITLE
Ckeditor does not work in iPad 

### ISSUE THREAD

**Issue by motor2hg** [sedteam/Seditio#26]
Ckeditor works fine in a browser on a computer, but does not work in Safari on an iPad. It won't connect. It won't connect.

**Comment by avego** [comment]
I have no way to test on a Mac :(
@motor2hg, what is output error console log in Safari?

**Comment by motor2hg** [comment]
Yes, in Mac OSX Safari also does not work. Errors:
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(анонимная функция) (plugin.js:28)
[Error] TypeError: null is not an object (evaluating 'h.icons')
	(анонимная функция) (ckeditor.js:267:254)
	(анонимная функция) (ckeditor.js:266:248)
	y (ckeditor.js:261:198)
	z (ckeditor.js:261:338)
	x (ckeditor.js:261:421)
	(анонимная функция) (ckeditor.js:262:362)

**Comment by motor2hg** [comment]
On Mac OS, Opera and Firefox work without error in the browser. Error only in Safari.

**Comment by avego** [comment]
Thank's
**plugin.js:28** - seems to swear at the **pasteUploadImage** plugin

please replace in **plugins/ckeditor/lib4/sed_config.js**

**config.extraPlugins = 'more,uploadimage,uploadwidget,layoutmanager,pasteUploadImage';**

on

**config.extraPlugins = 'more,uploadimage,uploadwidget,layoutmanager';**

and see log

**Comment by motor2hg** [comment]
Now it works, no errors

**Comment by motor2hg** [comment]
Uploaded the latest release doesn't work again. I had to change again in plugins/ckeditor/lib4/sed_config.js

config.extraPlugins = 'more,uploadimage,uploadwidget,layoutmanager,pasteUploadImage';

on

config.extraPlugins = 'more,uploadimage,uploadwidget,layoutmanager';

After that it works fine.
