### ISSUE TITLE
Upload image.

### ISSUE THREAD

**Issue by motor2hg** [sedteam/Seditio#29]
I noticed a certain peculiarity, if we save 1.jpg to the desktop running Windows 10, we select this image when creating an article, we save the article. Now let's create a new article, and before creating it, delete 1.jpg and save another picture with the same name on the desktop 1.jpg. Select Load image and see the old 1.jpg instead of the new image. After saving the article, there will be an old picture and not a new one, even if you select it through the explorer. As if the old image with the same name is stuck in the cache and until you change the name of the new image, for example 2.jpg, you will not be able to get anything done.

**Comment by motor2hg** [comment]
Friends observation 2. I have 10 images on my desktop. Suppose I add these images to News and Articles, then in my personal file storage there will be 20 such images. When uploading an image again, the system does not understand that it already exists in the personal storage. Maybe I'm wrong, but maybe I need to check the image for presence in pfs so as not to produce duplicates?

**Comment by motor2hg** [comment]
They are not physically duplicated in  /datas/users/

**Comment by avego** [comment]
Physically cropped and resized images are stored in a folder **/datas/resized/**

Cropping & Resizing function can be applied directly to tpl files. See index.tpl

**{PAGE_ROW_THUMB|crop_image(%s, 800, 600)}** or **{PAGE_ROW_THUMB|resize_image(%s, 800, 600)}**

where PAGE_ROW_THUMB - filename without path in PFS

**Comment by motor2hg** [comment]
When the transparent .png is resized it is written to the resize folder with a black background

**Comment by avego** [comment]
Fixed, now the alpha channel should be preserved when cropping and resizing. https://github.com/sedteam/Seditio/commit/742b2a8e48673d43a89124b41a726526715c8fb2
