### ISSUE TITLE
Admin panel is not mobile friendly

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#32]
Hello amro

admin panel is not mobile compatible, it is very difficult to manage from the phone

can you make it mobile friendly

**Comment by avego** [comment]
> Hello amro
> 
> admin panel is not mobile compatible, it is very difficult to manage from the phone
> 
> can you make it mobile friendly

Hi, Kaan
The adaptive admin skin will be in the next release (179-180). In the meantime, I'm fixing bugs to finally release Seditio 178.
