### ISSUE TITLE
User can see admin tooltips without admin rights

### ISSUE THREAD

**Issue by Antoinius** [sedteam/Seditio#37]
user without admin privileges can see admin options tooltips

![изображение_2022-06-22_115527163](https://user-images.githubusercontent.com/6013039/174987798-a8071d47-af8c-4ce7-b97b-bda17df8e859.png)

**Comment by avego** [comment]
It's already fixed, see commit 
please, see footer.php & footer.tpl (new parse section ADMIN)
https://github.com/sedteam/Seditio/commit/68f1c8c26bbb86ec5efe930b1c7bad649515c697
