### ISSUE TITLE
ckeditor full editor not working

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#50]
**Global toolbar for the group 'Administrators'** full editor not working
and Extended not working

**Comment by SeditioCMS** [comment]
ckeditor imguploader not working
https://prnt.sc/41mCNFouXUou
HTTP error occurred during file upload (404: File not found).

**Comment by avego** [comment]
> ckeditor imguploader not working https://prnt.sc/41mCNFouXUou HTTP error occurred during file upload (404: File not found).

Thanks Kaan! Paths are outdated. I fixed it.

d69d981789c639b395743536af9d4e78fceb0617

**Comment by avego** [comment]
> **Global toolbar for the group 'Administrators'** full editor not working and Extended not working

Fix CK global toolbar
ccf6008297a3978fe46f2bc700a8cb487047cb32

**Comment by SeditioCMS** [comment]
ckeditor.js?v=5:101          
GET http://localhost/sednew/plugins/ckeditor/lib4/skins/moonocolor/skin.js?t=ABCDFGDD 
net::ERR_ABORTED 404 (Not Found)
