### ISSUE TITLE
Does it work in PHP 8?

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#51]
I haven't tried if seditio will work on new version php 8.

**Comment by avego** [comment]
Kaan, in practice, I don't use php 8 yet
Our cms is written in a procedural style, so if there are errors, there will be few of them.
As we begin to use PHP 8 more actively, we will try to test and fix everything. In the meantime, we use php 7.4 and below, down to 5.4 )))

**Comment by SeditioCMS** [comment]
thanks, I'll let you know the errors when I try it in php 8.

**Comment by avego** [comment]
Ok. Most likely there will be errors on php 8))

**Comment by avego** [comment]
Over the past week, I have almost completely checked and fixed bugs on PHP 8.1.16
