### ISSUE TITLE
uploader.page.add.tags.php bug

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#53]
$first_thumb_array = isset($$newpageextra) ? trim($$newpageextra) : ''; 

$$ two

**Comment by avego** [comment]
This is not a bug, but the formation of a variable from a string. 
https://www.php.net/manual/en/language.variables.variable.php

**Comment by SeditioCMS** [comment]
ok thanks

In order to use variable variables with arrays, you have to resolve an ambiguity problem. That is, if you write $$a[1] then the parser needs to know if you meant to use $a[1] as a variable, or if you wanted $$a as the variable and then the [1] index from that variable. The syntax for resolving this ambiguity is: ${$a[1]} for the first case and ${$a}[1] for the second.
