### ISSUE TITLE
Can't choose from uploader plugin pfs

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#56]
video: https://streamable.com/7bawtq

**Comment by avego** [comment]
Thanks Kaan! I fixed it.

**Comment by SeditioCMS** [comment]
uploading images uploaded images are not deleted from the directory

**Comment by avego** [comment]
![image](https://user-images.githubusercontent.com/1747178/181227014-37650d74-073a-41c6-b294-b0da09ccf828.png)
Set option "Delete files physically from a PFS" to "Yes" in config uploader plugin
