### ISSUE TITLE
cookies problem

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#59]
$cfg['authmode'] = 1; 	Problem
Hoş geldiniz => **,** Welcome
Does not log in when cookies are enabled.

**Comment by avego** [comment]
There are no problems here. To authorize using only cookies, you must have a value selected in the "Remember me" drop-down list.
![image](https://user-images.githubusercontent.com/1747178/182146551-066f9103-da36-4e2d-b108-b3ccbc1c809f.png)

**Comment by SeditioCMS** [comment]
unfortunately i can't login
https://nt.web.tr/login
user: demo
pass: 123456

try please

**Comment by avego** [comment]
Most likely the problem is with your hosting. There may be a problem with saving temporary files in the /tmp folder

**Comment by avego** [comment]
Kaan, Did you find the reason problem?

**Comment by SeditioCMS** [comment]
> Kaan, Did you find the reason problem?

no i haven't found it yet
I didn't have time to research
looks like a cookie registration issue as you said

**Comment by SeditioCMS** [comment]
> Kaan, Did you find the reason problem?

I want to login from two computers with cookies but it is not working.
