### ISSUE TITLE
canonical url problem

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#60]
` <link rel="canonical" href="http://localhost/sednew/http://localhost/sednew/fiat-oto-yedek-parca/" />`

adding double url **list.inc.php**

this way no problem
`$out['canonical_url'] = sed_url("list", "c=".$c."&d=".$d);`

**page_alias** problem adding double url

**Comment by SeditioCMS** [comment]
And Above sed_selectbox_categories is code that needs to be cleared

`/* 
function sed_selectbox_categories($check, $name, $hideprivate = TRUE, $redirecturl = "", $additional="")
	{
	global $db_structure, $usr, $sed_cat, $L;

	$onchange = (!empty($redirecturl)) ? " onchange=\"sedjs.redirect(this)\"" : ""; 
	
	$result =  "<select name=\"$name\"".$onchange." size=\"1\">".$additional;

	foreach($sed_cat as $i => $x)
		{
		$display = ($hideprivate) ? sed_auth('page', $i, 'W') : TRUE;

		if (sed_auth('page', $i, 'R') && $i!='all' && $display)
			{
			$selected = ($i==$check) ? "selected=\"selected\"" : '';
			$result .= "<option value=\"".$redirecturl.$i."\" $selected> ".$x['tpath']."</option>";
			}
		}
	$result .= "</select>";
	return($result);
	}
*/`

**Comment by avego** [comment]
> ` <link rel="canonical" href="http://localhost/sednew/http://localhost/sednew/fiat-oto-yedek-parca/" />`
> 
> adding double url **list.inc.php**
> 
> this way no problem `$out['canonical_url'] = sed_url("list", "c=".$c."&d=".$d);`
> 
> **page_alias** problem adding double url

Hi, Kaan!
What are your settings here?
![image](https://user-images.githubusercontent.com/1747178/183709105-66a1c5eb-6300-429b-8258-b55a3a469c9e.png)

**Comment by avego** [comment]
https://github.com/sedteam/Seditio/commit/fb8e78ea0bc2dee4756032b0e830ce1dfd6eff62

**Comment by avego** [comment]
And if so? Is the problem gone? https://github.com/sedteam/Seditio/commit/fb8e78ea0bc2dee4756032b0e830ce1dfd6eff62

**Comment by SeditioCMS** [comment]
settings screen: https://prnt.sc/cy4unobjWgkG

I haven't tried yet
