### ISSUE TITLE
Can we do webp uploads?

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#61]
Hi Amro;
Can we webp uploaded images?
the library is here
https://raw.githubusercontent.com/verot/class.upload.php/master/src/class.upload.php
Docs: https://github.com/verot/class.upload.php/blob/master/README.md

**Comment by avego** [comment]
Hi, Kaan!

Too complex for me PHP Class. Upload webp I will not do in the engine, and it's not right. I made a webp generation on the fly (from jpg,png,gif loaded into pfs) with saving to the resizes folder. To do this, just modify functions.image.php

Example page.tpl:
src="{PAGE_THUMB|crop_image(%s, 865, 600, 0, 1)}"
src="{PAGE_THUMB|resize_image(%s, 865, 600, 0, 1)}"

Example list.tpl:
src="{LIST_ROW_THUMB|crop_image(%s, 600, 500, 0, 1)}"
src="{LIST_ROW_THUMB|resize_image(%s, 600, 500, 0, 1)}"

see https://github.com/sedteam/Seditio/commit/eec00e38053db52910e22787391e6db52437845e

**Comment by SeditioCMS** [comment]
i will try thanks i am not available this month
