### ISSUE TITLE
.gitignore #Mr Developer ?

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#64]
they don't exist

plugins/karma/*
plugins/ogmetas/*

**Comment by avego** [comment]
So it is necessary, Kaan :) and this is a secret))))

[Ogmetas](https://github.com/sedteam/Sedplugins/tree/main/ogmetas)

**Comment by SeditioCMS** [comment]
> So it is necessary, Kaan :) and this is a secret))))
> 
> [Ogmetas](https://github.com/sedteam/Sedplugins/tree/main/ogmetas)

please do not add your work :)

**Comment by SeditioCMS** [comment]
plugins/feedback :)
